db:
  url: aaaaaacterEncoding=utf8&useSSL=false
  username: aaa
  password: aaaa
author: zhanghaitao
packageName:
path:
    controller: com.mi.youpin.tuishouserver.controller
    service: com.mi.youpin.tuishouserver.service.impl
    interf: com.mi.youpin.tuishouserver.service
    dao: com.mi.youpin.tuishouserver.mapper
    entity: com.mi.youpin.tuishouserver.entity
    mapper: mapper
server:
  port: 7777
